spring:
  h2:
    console:
      enabled: true
      path: /h2-db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: ture
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
logging.level:
  org.hibernate.sql: trace
